task: detection

train_dataloader:
  dataset: 
    img_folder: C:/Users/jazzb/rt-deterv2/RT-DETRv2/dataset/Final_Dataset/train/images/
    ann_file: C:/Users/jazzb/rt-deterv2/RT-DETRv2/dataset/Final_Dataset/train/annotations.json


val_dataloader:
  dataset: 
    img_folder: C:/Users/jazzb/rt-deterv2/RT-DETRv2/dataset/Final_Dataset/val/images/
    ann_file: C:/Users/jazzb/rt-deterv2/RT-DETRv2/dataset/Final_Dataset/val/annotations.json
