# Inside configs/dataset/coco_detection.yml
task: detection

train_dataloader:
  dataset: 
    img_folder: C:/Users/jazzb/rt-deterv2/RT-DETRv2/dataset/RDD-Object-Detection-Dataset/train
    ann_file: C:/Users/jazzb/rt-deterv2/RT-DETRv2/dataset/RDD-Object-Detection-Dataset/train/_annotations.coco.json
    transforms:
      ops: ~

val_dataloader:
  dataset: 
    img_folder: C:/Users/jazzb/rt-deterv2/RT-DETRv2/dataset/RDD-Object-Detection-Dataset/valid
    ann_file: C:/Users/jazzb/rt-deterv2/RT-DETRv2/dataset/RDD-Object-Detection-Dataset/valid/_annotations.coco.json
    transforms:
      ops: ~